version: '3.3'

#Sevices
services:
 
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      monitoring_net:
      back_net:
        aliases:
          - post_db
          - comment_db

  post:
    image: ${DOCKER_HUB_USERNAME}/post:${POST_TAG}
    networks:
      monitoring_net:
      back_net:
      front_net:
        aliases:
          - post
    depends_on:
      - post_db

  comment:
    container_name: comment
    image: ${DOCKER_HUB_USERNAME}/comment:${COMMENT_TAG}
    networks:
      front_net:
      back_net:
      monitoring_net:
    depends_on:
      - post_db

  ui:
    image: ${DOCKER_HUB_USERNAME}/ui:${UI_TAG}
    ports:
      - ${UI_PORT_HOST}:9292/tcp
    networks:
        front_net:
        monitoring_net:
    depends_on:
      - post
      - comment    

#Volumes
volumes:
  post_db:
  prometheus_data:
  
#Networks
networks:
  front_net:
  back_net:
  monitoring_net:
    external: true

            

