version: '3.3'

#Sevices
services:

  prometheus:
    image: ${DOCKER_HUB_USERNAME}/prometheus
    networks:
      reddit:
    ports:
        - '9090:9090'
    volumes:
        - prometheus_data:/prometheus
    command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--storage.tsdb.retention=1d'

        
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      reddit:
        aliases:
          - post_db
          - comment_db

  post:
    image: ${DOCKER_HUB_USERNAME}/post:${POST_TAG}
    networks:
      reddit:
        aliases:
          - post
    depends_on:
      - post_db

  comment:
    image: ${DOCKER_HUB_USERNAME}/comment:${COMMENT_TAG}
    networks:
      reddit:
        aliases:
          - comment
    depends_on:
      - post_db

  ui:
    image: ${DOCKER_HUB_USERNAME}/ui:${UI_TAG}
    ports:
      - ${UI_PORT_HOST}:9292/tcp
    networks:
        reddit:
    depends_on:
      - post
      - comment
  

#Volumes
volumes:
  post_db:
  prometheus_data:
  
#Networks
networks:
  reddit:

            

