version: '3.3'

#Sevices
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build:
      context: ./ui
      dockerfile: ${Dockerfile_ui}
    image: ${DOCKER_HUB_USERNAME}/ui:${UI_TAG}
    ports:
      - ${UI_PORT_HOST}:9292/tcp
    networks:
      front_net:
    depends_on:
      - post
      - comment

  post:
    build:
      context: ./post-py
      dockerfile: ${Dockerfile_post}
    image: ${DOCKER_HUB_USERNAME}/post:${POST_TAG}
    networks:
      back_net:
      front_net:
        aliases:
          - post
    depends_on:
      - post_db

  comment:
    build:
      context: ./comment
      dockerfile: ${Dockerfile_comment}
    image: ${DOCKER_HUB_USERNAME}/comment:${COMMENT_TAG}
    networks:
      front_net:
        aliases:
          - comment
      back_net:
    depends_on:
      - post_db
#Volumes
volumes:
  post_db:
#Networks
networks:
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
  back_net:
        driver: bridge
        ipam:
          driver: default
          config:
            - subnet: 10.0.2.0/24
