version: '3.3'

#Sevices
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  
  ui:
    image: ${DOCKER_HUB_USERNAME}/ui:${UI_TAG}
    ports:
      - ${UI_PORT_HOST}:9292/tcp
    networks:
      front_net:
    depends_on:
      - post
      - comment

  post:
    image: ${DOCKER_HUB_USERNAME}/post:${POST_TAG}
    networks:
      back_net:
      front_net:
        aliases:
          - post
    depends_on:
      - post_db

  comment:
    image: ${DOCKER_HUB_USERNAME}/comment:${COMMENT_TAG}
    networks:
      front_net:
        aliases:
          - comment
      back_net:
    depends_on:
      - post_db
  
  prometheus:
    image: ${DOCKER_HUB_USERNAME}/prometheus
    networks:
      back_net:
      front_net:
    ports:
        - '9090:9090'
    volumes:
        - prometheus_data:/prometheus
    command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--storage.tsdb.retention=1d'
#Volumes
volumes:
  post_db:
  prometheus_data:
  
#Networks
networks:
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
  back_net:
        driver: bridge
        ipam:
          driver: default
          config:
            - subnet: 10.0.2.0/24
            

