version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - reddit
  ui:
    build: ./ui
    image: maksov/ui:3.0
    ports:
      - 9292:9292/tcp
    networks:
      - reddit
  post:
    build: ./post-py
    image: maksov/post:1.0
    networks:
      - reddit
  comment:
    build: ./comment
    image: maksov/comment:2.0
    networks:
      - reddit

volumes:
  post_db:

networks:
  reddit:
