groups:
 - name: alert.rules
   rules:
   - alert: InstanceDown
     expr: up == 0
     for: 1m
     labels:
      severity: page
     annotations:
      descriptions: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute'
      summary: 'Instance {{ $labels.instance }} down'
   - alert: UIResponseHigh
     expr: histogram_quantile(0.95, sum(rate(ui_request_latency_seconds_bucket[5m])) by (le)) > 0.5
     for: 1m
     annotations:
      descriptions: 'UI service takes long http responses'
      summary: 'High response time of UI service'
   - alert: DBLatency
     expr: histogram_quantile(0.95, sum(rate(post_read_db_seconds_bucket[5m])) by (le)) > 0.5
     for: 1m
     annotations:
      descriptions: '{{ $labels.instance }} has high latency from db'
      summary: 'High latency of db request on {{ $labels.instance }}'



      




