---

global:
    scrape_interval: '5s'

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets:
          - 'localhost:9090'
    - job_name: 'docker'
      static_configs:
        - targets:
          - '172.18.0.1:9323'
    
    - job_name: 'ui'
      static_configs:
        - targets:
           - 'ui:9292'
    
    - job_name: 'comment'
      static_configs:
        - targets:
          - 'comment:9292'

    - job_name: 'post'
      static_configs:
        - targets:
          - 'post:5000'

    - job_name: 'node'
      static_configs:
        - targets:
          - 'node-exporter:9100'
    
    - job_name: 'mongodb'
      static_configs:
        - targets:
          - 'mongodb-exporter:9104'

    - job_name: 'blackbox'
      metrics_path: /probe
      params:
        module: [http_2xx]
      static_configs:
        - targets:
          - http://comment:9292/healthcheck
          - http://post:5000/healthcheck
          - http://ui:9292
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-exporter:9115

    - job_name: 'cadvisor'
      static_configs:
        - targets:
            - 'cadvisor:8080'

    - job_name: 'stackdriver-exporter'
      static_configs:
        - targets:
          - 'stackdriver:9255'
     
rule_files:
 - "alerts.yml"

alerting:
 alertmanagers:
 - scheme: http
   static_configs:
   - targets:
     - "alertmanager:9093"
