---
global:
    scrape_interval: '5s'
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets:
            - 'localhost: 9090'
    - job_name: 'ui'
      statisic_configs:
        - targets:
         - 'ui:9292'
    - job_name: 'comment'
      static_configs:
        - targets:
            - 'comment:9292'
            
  